name: Daily Mantis Bot

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - run: pip install requests python-dotenv

      - run: python mantis.py